
if(MSVC)
    set(COMPILER_FLAGS /W4 /WX)
else()
    set(COMPILER_FLAGS -Wall -Wextra -Wpedantic -Werror)
endif()

set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g -O0")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMPILER_FLAGS}")

